### PR TITLE
Use Redux in React components.

### PR DESCRIPTION
**Pull request by UbdaNam**
## What does this PR do?

This PR is raised to implement the following features: 👍 :

- [x] Add initial mock book list 
- [x] Add book functionality added
- [x] Remove book functionality added
- [x] Use Gitflow 

## Description of the tasks completed 👇 

- [x] Use Redux in React components
- [x] Add bable to transpile modern JavaScript syntax into code that can run in all environments when writing React components
- [x] Use the linter tool that analyzes my source code to flag programming errors, bugs, stylistic errors, and suspicious constructs. 💯 
- [x] Check the accessibility of this project which means that websites, tools, and technologies are designed and developed so that people with disabilities ♿ can use them. For more information about Web accessibility [Click here](https://github.com/microverseinc/curriculum-html-css/blob/main/accessibility.md)☺️
     

  
## How should it be tested

Clone the repository
```
git clone https://github.com/UbdaNam/bookstore.git
```
Navigate to the folder
```
cd bookstore
```
Checkout the branch
```
git checkout Add-redux
```
Run app
```
npm start
```

#### Thanks for reviewing my PR 😊

### CODE REVIEW

**Review by AlphaNtihinduka — APPROVED** [review]
# STATUS: APPROVED :green_circle: :clap: 
## Hi @UbdaNam 🙋‍♂️, 

Your project is complete!  There is nothing else to say other than... Great job 👏 

approved-accepted

Congratulations! 🎉 
TO HIGHLIGHT:

- Ability to pass store in provider ✔️ 
- Proper use of useState react hook ✔️ 
- Well-structured files :heavy_check_mark: 

Now you can merge this branch and move on :1st_place_medal: 


## Optional suggestions
- No optional suggestions at moment.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :four_leaf_clover:

**Comment by UbdaNam** [comment]
Hi, @AlphaNtihinduka thank you for reviewing my PR. You mean to add a filtering option using category right?

**Comment by AlphaNtihinduka** [comment]
Hello @UbdaNam what are trying to refer to please? Kindly try as much as possible to clarify the question, to see where I can help.

**Comment by UbdaNam** [comment]
> Hello @UbdaNam what are trying to refer to please? Kindly try as much as possible to clarify the question, to see where I can help.

@AlphaNtihinduka I meant your optional suggestion, I didn't understand it well

**Comment by AlphaNtihinduka** [comment]
> > Hello @UbdaNam what are trying to refer to please? Kindly try as much as possible to clarify the question, to see where I can help.
> 
> @AlphaNtihinduka I meant your optional suggestion, I didn't understand it well

Hello @UbdaNam, I apologize for the delayed reply. Please you may consider ignoring the default message attached. However, to avoid confusion, I have updated the review summary. Kindly let me know if there is further support needed. Thank you.

**Pull request merged**
